version: '3'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    volumes:
      - ./sqlite/db/:/root/db/
      - ./sqlite/init.sql:/root/db/init.sql
    command: todolist.db ".read init.sql" # create the database and tables

  cask-sqlite-app:
    image: cask-sqlite-app:latest
    volumes:
      - ./sqlite/db/:/sqlite/db/
    ports:
      - "8081:8081"
